services:
  panel:
    build:
      args:
        user: fralberti
        uid: 1001
      context: ./
      dockerfile: Dockerfile
    image: enigmaimgv2
    container_name: enigmacontv2
    restart: unless-stopped
    working_dir: /home
    volumes:
      - ./data/:/home/data
      - ./output/:/home/output








